name: Bug
description: Make sure you complete the template. Otherwise, it will be closed without further explanation!
title: "[Bug] (Replace this with your title)"
labels: bug
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
      
- type: checkboxes
  attributes:
    label: Have you read the FAQ?
    description: Make sure you visit the [**FAQ**](https://github.com/qnblackcat/uYouPlus/wiki/FAQ) page first!
    options:
    - label: Yes, I read the FAQ
      required: true
    
- type: textarea
  attributes:
    label: Device info
    description: 
    value: |
        - iOS/iPadOS version:
        - Device model:
        - Sideload tool (Ex: AltStore, Sideloadly, TrollStore,...):
        - The specific version of uYouPlus: _**latest** or **newest** is NOT a version number!!_
    render: markdown
  validations:
    required: true

- type: textarea
  attributes:
    label: Describe the bug
    description: 
  validations:
    required: true

- type: textarea
  attributes:
    label: Steps to reproduce the issue
    description: Please attach videos or screenshots if possible
    placeholder: |
      1. 
      2. 
      3. 
  validations:
    required: true


